In [4]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 12.7 MB/s  0:00:0013.8 MB/s eta 0:00:01
Downloading numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 11.9 MB/s  0:00:002.4 MB/s eta 0:00:01:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]━━━━ 1/2 [pandas]
Successfully installed numpy-2.5.2 pandas-3.0.5
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [7]:
import os

In [8]:
os.listdir()

['SaaS_Analytics_Analysis.ipynb.ipynb',
 'ravenstack_feature_usage.csv',
 'ravenstack_subscriptions.csv',
 'ravenstack_support_tickets.csv',
 'ravenstack_churn_events.csv',
 'README.md',
 '.ipynb_checkpoints',
 'ravenstack_accounts.csv']

In [2]:
accounts = pd.read_csv("ravenstack_accounts.csv")

In [10]:
accounts.head()

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True

In [12]:
accounts.shape

(500, 10)

In [13]:
accounts.columns.tolist()

['account_id',
 'account_name',
 'industry',
 'country',
 'signup_date',
 'referral_source',
 'plan_tier',
 'seats',
 'is_trial',
 'churn_flag']

In [14]:
accounts.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    str
 1   account_name     500 non-null    str
 2   industry         500 non-null    str
 3   country          500 non-null    str
 4   signup_date      500 non-null    str
 5   referral_source  500 non-null    str
 6   plan_tier        500 non-null    str
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), int64(1), str(7)
memory usage: 32.4 KB

In [3]:
subscriptions = pd.read_csv("ravenstack_subscriptions.csv")
feature_usage = pd.read_csv("ravenstack_feature_usage.csv")
support_tickets = pd.read_csv("ravenstack_support_tickets.csv")
churn_events = pd.read_csv("ravenstack_churn_events.csv")

In [16]:
tables = {
    "Subscriptions": subscriptions,
    "Feature Usage": feature_usage,
    "Support Tickets": support_tickets,
    "Churn Events": churn_events
}

for name, df in tables.items():
    print(f"\n--- {name} ---")
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())

--- Subscriptions ---
Shape: (5000, 14)
Columns: ['subscription_id', 'account_id', 'start_date', 'end_date', 'plan_tier', 'seats', 'mrr_amount', 'arr_amount', 'is_trial', 'upgrade_flag', 'downgrade_flag', 'churn_flag', 'billing_frequency', 'auto_renew_flag']

--- Feature Usage ---
Shape: (25000, 8)
Columns: ['usage_id', 'subscription_id', 'usage_date', 'feature_name', 'usage_count', 'usage_duration_secs', 'error_count', 'is_beta_feature']

--- Support Tickets ---
Shape: (2000, 9)
Columns: ['ticket_id', 'account_id', 'submitted_at', 'closed_at', 'resolution_time_hours', 'priority', 'first_response_time_minutes', 'satisfaction_score', 'escalation_flag']

--- Churn Events ---
Shape: (600, 9)
Columns: ['churn_event_id', 'account_id', 'churn_date', 'reason_code', 'refund_amount_usd', 'preceding_upgrade_flag', 'preceding_downgrade_flag', 'is_reactivation', 'feedback_text']

In [17]:
tables = {
    "Accounts": accounts,
    "Subscriptions": subscriptions,
    "Feature Usage": feature_usage,
    "Support Tickets": support_tickets,
    "Churn Events": churn_events
}

for name, df in tables.items():
    print(f"\n{'=' * 50}")
    print(f"{name}")
    print(f"{'=' * 50}")

    print("Shape:", df.shape)
    print("\nMissing values:")
    print(df.isnull().sum())

    print("\nDuplicate rows:", df.duplicated().sum())

    print("\nUnique values:")
    print(df.nunique())

==================================================
Accounts
==================================================
Shape: (500, 10)

Missing values:
account_id         0
account_name       0
industry           0
country            0
signup_date        0
referral_source    0
plan_tier          0
seats              0
is_trial           0
churn_flag         0
dtype: int64

Duplicate rows: 0

Unique values:
account_id         500
account_name       500
industry             5
country              7
signup_date        370
referral_source      5
plan_tier            3
seats               73
is_trial             2
churn_flag           2
dtype: int64

==================================================
Subscriptions
==================================================
Shape: (5000, 14)

Missing values:
subscription_id         0
account_id              0
start_date              0
end_date             4514
plan_tier               0
seats                   0
mrr_amount              0
arr_amount              0
is_trial                0
upgrade_flag            0
downgrade_flag          0
churn_flag              0
billing_frequency       0
auto_renew_flag         0
dtype: int64

Duplicate rows: 0

Unique values:
subscription_id      5000
account_id            500
start_date            625
end_date              208
plan_tier               3
seats                 123
mrr_amount            306
arr_amount            306
is_trial                2
upgrade_flag            2
downgrade_flag          2
churn_flag              2
billing_frequency       2
auto_renew_flag         2
dtype: int64

==================================================
Feature Usage
==================================================
Shape: (25000, 8)

Missing values:
usage_id               0
subscription_id        0
usage_date             0
feature_name           0
usage_count            0
usage_duration_secs    0
error_count            0
is_beta_feature        0
dtype: int64

Duplicate rows: 0

Unique values:
usage_id               24979
subscription_id         4967
usage_date               731
feature_name              40
usage_count               27
usage_duration_secs     4168
error_count                9
is_beta_feature            2
dtype: int64

==================================================
Support Tickets
==================================================
Shape: (2000, 9)

Missing values:
ticket_id                        0
account_id                       0
submitted_at                     0
closed_at                        0
resolution_time_hours            0
priority                         0
first_response_time_minutes      0
satisfaction_score             825
escalation_flag                  0
dtype: int64

Duplicate rows: 0

Unique values:
ticket_id                      2000
account_id                      492
submitted_at                    671
closed_at                      1893
resolution_time_hours            72
priority                          4
first_response_time_minutes     180
satisfaction_score                3
escalation_flag                   2
dtype: int64

==================================================
Churn Events
==================================================
Shape: (600, 9)

Missing values:
churn_event_id                0
account_id                    0
churn_date                    0
reason_code                   0
refund_amount_usd             0
preceding_upgrade_flag        0
preceding_downgrade_flag      0
is_reactivation               0
feedback_text               148
dtype: int64

Duplicate rows: 0

Unique values:
churn_event_id              600
account_id                  352
churn_date                  311
reason_code                   6
refund_amount_usd           142
preceding_upgrade_flag        2
preceding_downgrade_flag      2
is_reactivation               2
feedback_text                 3
dtype: int64

In [18]:
subscriptions.groupby("churn_flag")["end_date"].apply(
    lambda x: x.isna().sum()
)

churn_flag
False    4514
True        0
Name: end_date, dtype: int64

In [19]:
subscriptions[
    subscriptions["end_date"].isna()
][
    ["account_id", "start_date", "churn_flag", "auto_renew_flag"]
]

     account_id  start_date  churn_flag  auto_renew_flag
1      A-9b9fe9  2024-06-11       False             True
2      A-659280  2024-11-25       False            False
4      A-ba6516  2024-01-10       False             True
5      A-fa2041  2024-08-13       False             True
6      A-417d2f  2023-12-30       False             True
...         ...         ...         ...              ...
4995   A-fa2041  2024-10-27       False             True
4996   A-db5e9e  2024-12-05       False            False
4997   A-443f6f  2024-12-15       False             True
4998   A-c7ffc2  2023-05-25       False             True
4999   A-ccb686  2024-12-06       False             True

[4514 rows x 4 columns]

In [20]:
subscriptions[subscriptions["end_date"].isna()][
    ["account_id", "start_date", "churn_flag", "auto_renew_flag"]
].head(20)

   account_id  start_date  churn_flag  auto_renew_flag
1    A-9b9fe9  2024-06-11       False             True
2    A-659280  2024-11-25       False            False
4    A-ba6516  2024-01-10       False             True
5    A-fa2041  2024-08-13       False             True
6    A-417d2f  2023-12-30       False             True
7    A-5f2961  2024-12-23       False             True
8    A-cc8c8f  2024-11-27       False            False
9    A-80eeb6  2024-10-27       False            False
10   A-f03140  2024-02-06       False             True
11   A-3a5ad8  2024-12-25       False             True
12   A-f17767  2023-09-17       False             True
13   A-7920cc  2024-07-17       False             True
14   A-8ae3fc  2024-10-12       False             True
15   A-0cc442  2024-09-18       False             True
18   A-b30291  2024-04-25       False             True
19   A-e19ff6  2024-03-06       False             True
20   A-dec005  2024-03-31       False             True
22   A-f5641b  2024-11-30       False             True
23   A-aa9511  2024-02-09       False             True
24   A-075038  2024-02-25       False             True

In [21]:
support_tickets[support_tickets["satisfaction_score"].isna()][
    ["account_id", "priority", "resolution_time_hours", "escalation_flag"]
].head(20)

   account_id priority  resolution_time_hours  escalation_flag
0    A-712f1c     high                   27.0            False
1    A-e43bf7   urgent                   27.0            False
4    A-6f8ad2   medium                   26.0            False
5    A-94c3cd   medium                    9.0            False
8    A-b179bf   urgent                   16.0            False
10   A-157070      low                   42.0            False
12   A-4e0e85   medium                   50.0            False
15   A-40a557     high                   69.0            False
16   A-05f0e5      low                   36.0            False
18   A-410e86     high                    3.0            False
19   A-ac9111      low                   14.0            False
22   A-158f4e     high                   11.0            False
31   A-7c4956     high                   19.0            False
32   A-3ce5b8      low                   50.0            False
39   A-ee42db   urgent                   57.0            False
40   A-e98302      low                   66.0            False
41   A-503d5a   urgent                    9.0            False
43   A-f5641b     high                   55.0            False
44   A-fb186e   medium                   42.0            False
54   A-9208f0      low                   70.0            False

In [22]:
for name, df in tables.items():
    print(f"\n{'=' * 50}")
    print(name)
    print("=" * 50)
    print(df.dtypes)

==================================================
Accounts
==================================================
account_id           str
account_name         str
industry             str
country              str
signup_date          str
referral_source      str
plan_tier            str
seats              int64
is_trial            bool
churn_flag          bool
dtype: object

==================================================
Subscriptions
==================================================
subscription_id        str
account_id             str
start_date             str
end_date               str
plan_tier              str
seats                int64
mrr_amount           int64
arr_amount           int64
is_trial              bool
upgrade_flag          bool
downgrade_flag        bool
churn_flag            bool
billing_frequency      str
auto_renew_flag       bool
dtype: object

==================================================
Feature Usage
==================================================
usage_id                 str
subscription_id          str
usage_date               str
feature_name             str
usage_count            int64
usage_duration_secs    int64
error_count            int64
is_beta_feature         bool
dtype: object

==================================================
Support Tickets
==================================================
ticket_id                          str
account_id                         str
submitted_at                       str
closed_at                          str
resolution_time_hours          float64
priority                           str
first_response_time_minutes      int64
satisfaction_score             float64
escalation_flag                   bool
dtype: object

==================================================
Churn Events
==================================================
churn_event_id                  str
account_id                      str
churn_date                      str
reason_code                     str
refund_amount_usd           float64
preceding_upgrade_flag         bool
preceding_downgrade_flag       bool
is_reactivation                bool
feedback_text                   str
dtype: object

In [23]:
print(accounts["signup_date"].head())
print(subscriptions["start_date"].head())
print(feature_usage["usage_date"].head())
print(support_tickets["submitted_at"].head())
print(churn_events["churn_date"].head())

0    2024-10-16
1    2023-08-17
2    2024-08-27
3    2023-08-27
4    2024-10-27
Name: signup_date, dtype: str
0    2023-12-23
1    2024-06-11
2    2024-11-25
3    2024-11-23
4    2024-01-10
Name: start_date, dtype: str
0    2023-07-27
1    2023-08-07
2    2023-12-07
3    2024-07-28
4    2024-12-02
Name: usage_date, dtype: str
0    2023-07-27
1    2024-07-08
2    2024-10-17
3    2024-09-08
4    2024-11-30
Name: submitted_at, dtype: str
0    2024-10-27
1    2024-06-25
2    2024-11-12
3    2023-11-01
4    2024-12-30
Name: churn_date, dtype: str

In [25]:
accounts["signup_date"] = pd.to_datetime(accounts["signup_date"])

In [26]:
accounts["signup_date"].dtype

dtype('<M8[us]')

In [23]:
subscriptions["start_date"] = pd.to_datetime(subscriptions["start_date"])
subscriptions["end_date"] = pd.to_datetime(subscriptions["end_date"])

feature_usage["usage_date"] = pd.to_datetime(feature_usage["usage_date"])

support_tickets["submitted_at"] = pd.to_datetime(support_tickets["submitted_at"])
support_tickets["closed_at"] = pd.to_datetime(support_tickets["closed_at"])

churn_events["churn_date"] = pd.to_datetime(churn_events["churn_date"])

In [24]:
date_columns = {
    "Accounts": accounts["signup_date"],
    "Subscriptions - start": subscriptions["start_date"],
    "Subscriptions - end": subscriptions["end_date"],
    "Feature Usage": feature_usage["usage_date"],
    "Support Tickets - submitted": support_tickets["submitted_at"],
    "Support Tickets - closed": support_tickets["closed_at"],
    "Churn Events": churn_events["churn_date"]
}

for name, column in date_columns.items():
    print(name, "→", column.dtype)

Accounts → str
Subscriptions - start → datetime64[us]
Subscriptions - end → datetime64[us]
Feature Usage → datetime64[us]
Support Tickets - submitted → datetime64[us]
Support Tickets - closed → datetime64[us]
Churn Events → datetime64[us]

In [29]:
subscriptions[
    subscriptions["end_date"].notna() &
    (subscriptions["end_date"] < subscriptions["start_date"])
]

Empty DataFrame
Columns: [subscription_id, account_id, start_date, end_date, plan_tier, seats, mrr_amount, arr_amount, is_trial, upgrade_flag, downgrade_flag, churn_flag, billing_frequency, auto_renew_flag]
Index: []

In [30]:
subscriptions["mrr_amount"]
subscriptions["arr_amount"]

0       33432
1        9996
2           0
3       11940
4       64476
        ...
4995    42984
4996    13524
4997    14700
4998    77616
4999    23880
Name: arr_amount, Length: 5000, dtype: int64

In [31]:
subscriptions[["mrr_amount", "arr_amount"]].head(20)

    mrr_amount  arr_amount
0         2786       33432
1          833        9996
2            0           0
3          995       11940
4         5373       64476
5          735        8820
6          796        9552
7          304        3648
8         4577       54924
9         1078       12936
10        1323       15876
11           0           0
12        1274       15288
13         741        8892
14           0           0
15        2205       26460
16           0           0
17         152        1824
18          95        1140
19         392        4704

In [32]:
subscriptions[
    subscriptions["arr_amount"] != subscriptions["mrr_amount"] * 12
]

Empty DataFrame
Columns: [subscription_id, account_id, start_date, end_date, plan_tier, seats, mrr_amount, arr_amount, is_trial, upgrade_flag, downgrade_flag, churn_flag, billing_frequency, auto_renew_flag]
Index: []

In [33]:
subscriptions[subscriptions["seats"] <= 0]

Empty DataFrame
Columns: [subscription_id, account_id, start_date, end_date, plan_tier, seats, mrr_amount, arr_amount, is_trial, upgrade_flag, downgrade_flag, churn_flag, billing_frequency, auto_renew_flag]
Index: []

In [34]:
accounts["industry"].value_counts()

industry
DevTools         113
FinTech          112
Cybersecurity    100
HealthTech        96
EdTech            79
Name: count, dtype: int64

In [35]:
accounts["industry"].value_counts(normalize=True) * 100

industry
DevTools         22.6
FinTech          22.4
Cybersecurity    20.0
HealthTech       19.2
EdTech           15.8
Name: proportion, dtype: float64

In [36]:
accounts.groupby("industry")["churn_flag"].mean() * 100

industry
Cybersecurity    16.000000
DevTools         30.973451
EdTech           16.455696
FinTech          22.321429
HealthTech       21.875000
Name: churn_flag, dtype: float64

In [37]:
pd.crosstab(
    accounts["industry"],
    accounts["plan_tier"],
    normalize="index"
) * 100

plan_tier          Basic  Enterprise        Pro
industry
Cybersecurity  31.000000   31.000000  38.000000
DevTools       31.858407   30.973451  37.168142
EdTech         35.443038   30.379747  34.177215
FinTech        30.357143   33.035714  36.607143
HealthTech     40.625000   28.125000  31.250000

In [38]:
accounts.groupby("plan_tier")["churn_flag"].mean() * 100

plan_tier
Basic         22.023810
Enterprise    22.077922
Pro           21.910112
Name: churn_flag, dtype: float64

In [6]:
print(accounts.shape)
print(support_tickets.shape)

(500, 10)
(2000, 9)

In [7]:
accounts["account_id"].nunique()

500

In [8]:
support_tickets["account_id"].nunique()

492

In [9]:
accounts_support = accounts.merge(
    support_tickets,
    on="account_id",
    how="left"
)

In [10]:
accounts_support.shape

(2008, 18)

In [11]:
accounts_support["ticket_id"].isna().sum()

np.int64(8)

In [12]:
accounts_support["has_support_ticket"] = (
    accounts_support["ticket_id"].notna()
)

In [13]:
accounts_support.groupby("has_support_ticket")["churn_flag"].mean() * 100

has_support_ticket
False    25.0
True     21.6
Name: churn_flag, dtype: float64

In [14]:
account_support_summary = (
    accounts_support
    .groupby("account_id")
    .agg(
        has_support_ticket=("ticket_id", lambda x: x.notna().any())
    )
    .reset_index()
)

In [15]:
account_support_summary = account_support_summary.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

In [16]:
account_support_summary.groupby(
    "has_support_ticket"
)["churn_flag"].mean() * 100

has_support_ticket
False    25.00000
True     21.95122
Name: churn_flag, dtype: float64

In [17]:
account_support_summary["has_support_ticket"].value_counts()

has_support_ticket
True     492
False      8
Name: count, dtype: int64

In [18]:
ticket_count = (
    support_tickets
    .groupby("account_id")
    .size()
    .reset_index(name="ticket_count")
)

In [19]:
ticket_churn = ticket_count.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

In [20]:
ticket_count.head(20)

   account_id  ticket_count
0    A-00bed1             4
1    A-00cac8             2
2    A-0158bb             1
3    A-016043             3
4    A-019782             2
5    A-029f69             2
6    A-02cd81             3
7    A-02fac6             6
8    A-034368             5
9    A-0354fe             4
10   A-038089             6
11   A-0532a9             8
12   A-054577             1
13   A-05d3b3             6
14   A-05f0e5             4
15   A-0651a4             4
16   A-068fc6             5
17   A-075038             2
18   A-089363             3
19   A-08e34e             3

In [21]:
ticket_churn.head(20)

   account_id  ticket_count  churn_flag
0    A-00bed1             4       False
1    A-00cac8             2       False
2    A-0158bb             1       False
3    A-016043             3       False
4    A-019782             2       False
5    A-029f69             2       False
6    A-02cd81             3       False
7    A-02fac6             6       False
8    A-034368             5       False
9    A-0354fe             4       False
10   A-038089             6        True
11   A-0532a9             8       False
12   A-054577             1       False
13   A-05d3b3             6       False
14   A-05f0e5             4       False
15   A-0651a4             4       False
16   A-068fc6             5       False
17   A-075038             2       False
18   A-089363             3       False
19   A-08e34e             3        True

In [22]:
ticket_churn.groupby("churn_flag")["ticket_count"].mean()

churn_flag
False    4.083333
True     4.000000
Name: ticket_count, dtype: float64

In [23]:
support_summary = (
    support_tickets
    .groupby("account_id")
    .agg(
        ticket_count=("ticket_id", "count"),
        avg_resolution_hours=("resolution_time_hours", "mean"),
        avg_first_response_minutes=("first_response_time_minutes", "mean"),
        avg_satisfaction=("satisfaction_score", "mean"),
        escalation_count=("escalation_flag", "sum")
    )
    .reset_index()
)

In [26]:
support_summary = support_summary.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

In [27]:
support_tickets.groupby("account_id")["resolution_time_hours"].mean()

account_id
A-00bed1    31.750000
A-00cac8    33.000000
A-0158bb    32.000000
A-016043    30.333333
A-019782    10.000000
              ...
A-fdfc91    28.800000
A-fe79a5    28.500000
A-ff3c73    35.500000
A-ff79f2    50.000000
A-ffc04f    17.714286
Name: resolution_time_hours, Length: 492, dtype: float64

In [28]:
support_summary.head(20)

,account_id,ticket_count,avg_resolution_hours,avg_first_response_minutes,avg_satisfaction,escalation_count,churn_flag_x,churn_flag_y,churn_flag
0,A-00bed1,4,31.750000,106.250000,4.000000,0,False,False,False
1,A-00cac8,2,33.000000,120.500000,NaN,0,False,False,False
2,A-0158bb,1,32.000000,50.000000,3.000000,0,False,False,False
3,A-016043,3,30.333333,78.000000,4.000000,0,False,False,False
4,A-019782,2,10.000000,107.000000,3.000000,0,False,False,False
5,A-029f69,2,42.000000,108.000000,3.000000,0,False,False,False
6,A-02cd81,3,17.333333,84.666667,4.500000,1,False,False,False
7,A-02fac6,6,23.333333,100.500000,4.000000,0,False,False,False
8,A-034368,5,41.200000,91.800000,4.000000,0,False,False,False
9,A-0354fe,4,20.000000,69.250000,4.000000,0,False,False,False
10,A-038089,6,30.166667,86.166667,3.666667,0,True,True,True
11,A-0532a9,8,30.750000,73.375000,3.000000,0,False,False,False
12,A-054577,1,46.000000,70.000000,4.000000,0,False,False,False
13,A-05d3b3,6,31.500000,48.333333,4.333333,0,False,False,False
14,A-05f0e5,4,20.000000,108.500000,4.000000,0,False,False,False
15,A-0651a4,4,29.250000,48.500000,4.000000,0,False,False,False
16,A-068fc6,5,38.800000,121.400000,4.333333,0,False,False,False
17,A-075038,2,43.500000,54.000000,3.000000,0,False,False,False
18,A-089363,3,35.000000,91.333333,3.666667,0,False,False,False
19,A-08e34e,3,43.000000,84.000000,3.000000,0,True,True,True

In [29]:
support_summary = support_summary.drop(
    columns=["churn_flag_x", "churn_flag_y"]
)

In [30]:
support_summary.groupby("churn_flag")["avg_resolution_hours"].mean()

churn_flag
False    36.450306
True     35.485483
Name: avg_resolution_hours, dtype: float64

In [31]:
support_summary.groupby("churn_flag")["avg_first_response_minutes"].mean()

churn_flag
False    89.581916
True     84.926947
Name: avg_first_response_minutes, dtype: float64

In [32]:
support_summary.groupby("churn_flag")["avg_satisfaction"].mean()

churn_flag
False    3.953395
True     4.002591
Name: avg_satisfaction, dtype: float64

In [33]:
support_summary.groupby("churn_flag")["escalation_count"].mean()

churn_flag
False    0.184896
True     0.222222
Name: escalation_count, dtype: float64

In [34]:
subscriptions.groupby("upgrade_flag")["churn_flag"].mean() * 100

upgrade_flag
False    9.841199
True     8.695652
Name: churn_flag, dtype: float64

In [5]:
subscriptions["upgrade_flag"].value_counts()

upgrade_flag
False    4471
True      529
Name: count, dtype: int64

In [7]:
subscriptions["account_id"].nunique()

500

In [8]:
subscriptions["account_id"].value_counts().describe()

count    500.0000
mean      10.0000
std        3.2713
min        2.0000
25%        7.0000
50%       10.0000
75%       12.0000
max       19.0000
Name: count, dtype: float64

In [9]:
subscriptions["upgrade_flag"].value_counts()

upgrade_flag
False    4471
True      529
Name: count, dtype: int64

In [10]:
subscriptions[subscriptions["upgrade_flag"]]["account_id"].nunique()

307

In [11]:
account_upgrade = (
    subscriptions
    .groupby("account_id")["upgrade_flag"]
    .any()
    .reset_index(name="has_upgraded")
)

In [12]:
account_upgrade = account_upgrade.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

In [13]:
account_upgrade.groupby("has_upgraded")["churn_flag"].mean() * 100

has_upgraded
False    23.834197
True     20.846906
Name: churn_flag, dtype: float64

In [14]:
subscription_count = (
    subscriptions
    .groupby("account_id")
    .size()
    .reset_index(name="subscription_count")
)

In [15]:
subscription_count.head(20)

   account_id  subscription_count
0    A-00bed1                  10
1    A-00cac8                   9
2    A-0158bb                   6
3    A-016043                  11
4    A-019782                   9
5    A-029f69                  16
6    A-02cd81                  14
7    A-02fac6                  11
8    A-034368                   5
9    A-0354fe                   7
10   A-038089                   3
11   A-039727                  15
12   A-0532a9                  10
13   A-054577                  16
14   A-05d3b3                  13
15   A-05f0e5                  12
16   A-0651a4                  15
17   A-068fc6                  10
18   A-075038                  14
19   A-089363                  14

In [16]:
subscription_count = subscription_count.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

In [17]:
subscription_count.groupby("churn_flag")["subscription_count"].mean()

churn_flag
False     9.917949
True     10.290909
Name: subscription_count, dtype: float64

In [26]:
completed_subscriptions = subscriptions[
    subscriptions["end_date"].notna()
].copy()

In [25]:
subscriptions["start_date"] = pd.to_datetime(subscriptions["start_date"])
subscriptions["end_date"] = pd.to_datetime(subscriptions["end_date"])

In [27]:
completed_subscriptions["subscription_days"] = (
    completed_subscriptions["end_date"]
    - completed_subscriptions["start_date"]
).dt.days

In [28]:
completed_subscriptions[["start_date", "end_date", "subscription_days"]].head(20)

    start_date   end_date  subscription_days
0   2023-12-23 2024-04-12                111
3   2024-11-23 2024-12-13                 20
16  2023-07-21 2024-08-03                379
17  2024-06-06 2024-08-13                 68
21  2024-12-04 2024-12-27                 23
29  2024-08-22 2024-09-28                 37
52  2024-01-14 2024-12-29                350
54  2024-09-18 2024-11-17                 60
64  2024-08-27 2024-12-11                106
73  2024-10-17 2024-12-04                 48
78  2024-12-25 2024-12-28                  3
86  2024-07-31 2024-09-04                 35
93  2024-11-09 2024-12-18                 39
120 2023-02-28 2023-06-15                107
124 2024-12-25 2024-12-28                  3
132 2023-08-13 2024-06-22                314
134 2024-11-08 2024-11-25                 17
140 2024-11-24 2024-12-05                 11
143 2024-01-17 2024-04-19                 93
168 2024-12-02 2024-12-19                 17

In [29]:
subscription_duration = (
    completed_subscriptions
    .groupby("account_id")["subscription_days"]
    .mean()
    .reset_index(name="avg_subscription_days")
)

In [30]:
subscription_duration = subscription_duration.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

In [31]:
subscription_duration.groupby(
    "churn_flag"
)["avg_subscription_days"].mean()

churn_flag
False    79.400000
True     94.085648
Name: avg_subscription_days, dtype: float64

In [32]:
subscription_duration["churn_flag"].value_counts()

churn_flag
False    240
True      72
Name: count, dtype: int64

In [33]:
subscription_duration.groupby("churn_flag")["avg_subscription_days"].describe()

,count,mean,std,min,25%,50%,75%,max
churn_flag,,,,,,,,
False,240.0,79.400000,92.985396,0.0,14.625,40.50,108.333333,466.0
True,72.0,94.085648,100.851174,2.0,25.750,60.25,126.625000,435.5

In [34]:
subscriptions["downgrade_flag"].value_counts()

downgrade_flag
False    4782
True      218
Name: count, dtype: int64

In [35]:
account_downgrade = (
    subscriptions
    .groupby("account_id")["downgrade_flag"]
    .any()
    .reset_index(name="has_downgraded")
)

In [36]:
account_downgrade = account_downgrade.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

In [37]:
account_downgrade.groupby("has_downgraded")["churn_flag"].mean() * 100

has_downgraded
False    22.600619
True     20.903955
Name: churn_flag, dtype: float64

In [38]:
subscriptions.groupby("account_id")["auto_renew_flag"].nunique().value_counts()

auto_renew_flag
2    429
1     71
Name: count, dtype: int64

In [39]:
churn_events["reason_code"].value_counts()

reason_code
features      114
support       104
budget        104
unknown        95
competitor     92
pricing        91
Name: count, dtype: int64

In [20]:
churn_analysis = churn_events.merge(
    accounts[["account_id", "industry"]],
    on="account_id",
    how="left"
)

In [41]:
churn_analysis.head(20)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text,industry
0,C-816288,A-c37cab,2024-10-27,pricing,4.03,False,False,False,switched to competitor,Cybersecurity
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,True,False,False,NaN,HealthTech
2,C-a174be,A-b07346,2024-11-12,budget,0.00,False,False,False,missing features,HealthTech
3,C-accb39,A-1e50e0,2023-11-01,budget,54.94,False,False,False,switched to competitor,Cybersecurity
4,C-92f889,A-956988,2024-12-30,unknown,0.00,False,True,True,too expensive,EdTech
5,C-a8ac26,A-b20d99,2024-03-04,features,0.00,False,False,False,missing features,HealthTech
6,C-2e2966,A-526d93,2024-07-10,features,34.40,True,False,False,NaN,HealthTech
7,C-ee531b,A-751bd4,2024-09-22,budget,0.00,False,False,False,NaN,Cybersecurity
8,C-e6a0f0,A-ccabf0,2024-10-31,features,0.00,False,False,False,too expensive,HealthTech
9,C-9328ba,A-0a62f5,2024-10-10,features,0.00,False,False,False,switched to competitor,FinTech
10,C-c89493,A-3ce5b8,2024-09-18,features,261.49,False,False,False,too expensive,FinTech
11,C-c54ef0,A-3b5cd1,2024-08-30,unknown,77.87,False,False,False,missing features,FinTech
12,C-bb3556,A-bcf664,2024-08-08,competitor,0.00,False,False,False,NaN,DevTools
13,C-875dc5,A-b9f5b1,2023-07-21,features,0.00,False,False,False,switched to competitor,Cybersecurity
14,C-c8f7b4,A-0dbdc6,2024-04-14,pricing,175.02,False,False,False,too expensive,Cybersecurity
15,C-865f19,A-c9bb3e,2024-07-29,pricing,0.00,False,False,False,switched to competitor,EdTech
16,C-102614,A-96e141,2024-07-22,budget,43.53,False,False,False,too expensive,DevTools
17,C-4ab0e2,A-e7a1e2,2024-09-08,support,0.00,True,False,False,missing features,Cybersecurity
18,C-742a59,A-812c5b,2024-05-11,support,11.83,False,False,False,missing features,DevTools
19,C-1f9cf2,A-1e50e0,2024-04-26,pricing,0.00,False,False,False,switched to competitor,Cybersecurity

In [21]:
pd.crosstab(
    churn_analysis["industry"],
    churn_analysis["reason_code"],
    normalize="index"
) * 100

reason_code,budget,competitor,features,pricing,support,unknown
industry,,,,,,
Cybersecurity,18.333333,14.166667,16.666667,11.666667,16.666667,22.500000
DevTools,19.014085,17.605634,18.309859,15.492958,19.014085,10.563380
EdTech,12.121212,11.111111,24.242424,17.171717,15.151515,20.202020
FinTech,18.750000,14.843750,14.843750,12.500000,20.312500,18.750000
HealthTech,17.117117,18.018018,22.522523,19.819820,14.414414,8.108108

In [43]:
usage_summary = (
    feature_usage
    .groupby("subscription_id")
    .agg(
        total_usage=("usage_count", "sum"),
        total_duration_secs=("usage_duration_secs", "sum"),
        total_errors=("error_count", "sum")
    )
    .reset_index()
)

In [44]:
usage_summary.head(20)

   subscription_id  total_usage  total_duration_secs  total_errors
0         S-001561           48                21604             3
1         S-0027d3           44                20848             0
2         S-003647           71                13018             3
3         S-003fc0           43                11933             1
4         S-004d19           18                 5616             0
5         S-004eb4           80                21159             2
6         S-006908           13                  403             1
7         S-006fed          104                39033             0
8         S-007e2c           49                12922             0
9         S-00837c           45                 8638             7
10        S-00866d           37                 1955             2
11        S-008cab           96                28356             8
12        S-008f3c            6                 1950             0
13        S-009027           54                19903             1
14        S-00ab51           49                13374             2
15        S-00b0bc            4                 2304             0
16        S-00bb84           81                20319             5
17        S-00dea4           63                16766             0
18        S-00f31d           40                12816             2
19        S-00fb6e           57                17714             0

In [45]:
usage_summary = usage_summary.merge(
    subscriptions[["subscription_id", "account_id"]],
    on="subscription_id",
    how="left"
)

In [46]:
usage_summary.head(20)

   subscription_id  total_usage  total_duration_secs  total_errors account_id
0         S-001561           48                21604             3   A-1b7577
1         S-0027d3           44                20848             0   A-e693b6
2         S-003647           71                13018             3   A-e36807
3         S-003fc0           43                11933             1   A-65c341
4         S-004d19           18                 5616             0   A-bece89
5         S-004eb4           80                21159             2   A-ab438f
6         S-006908           13                  403             1   A-d82ef9
7         S-006fed          104                39033             0   A-ac9111
8         S-007e2c           49                12922             0   A-cb5333
9         S-00837c           45                 8638             7   A-089363
10        S-00866d           37                 1955             2   A-05f0e5
11        S-008cab           96                28356             8   A-202b67
12        S-008f3c            6                 1950             0   A-e98302
13        S-009027           54                19903             1   A-1b7577
14        S-00ab51           49                13374             2   A-ae052e
15        S-00b0bc            4                 2304             0   A-089363
16        S-00bb84           81                20319             5   A-4f18f0
17        S-00dea4           63                16766             0   A-a6d261
18        S-00f31d           40                12816             2   A-410e86
19        S-00fb6e           57                17714             0   A-c16101

In [47]:
account_usage = (
    usage_summary
    .groupby("account_id")
    .agg(
        total_usage=("total_usage", "sum"),
        total_duration_secs=("total_duration_secs", "sum"),
        total_errors=("total_errors", "sum")
    )
    .reset_index()
)

In [48]:
account_usage.head(20)

   account_id  total_usage  total_duration_secs  total_errors
0    A-00bed1          514               143734            27
1    A-00cac8          602               171366            31
2    A-0158bb          364               122051            22
3    A-016043          490               132075            21
4    A-019782          562               160848            30
5    A-029f69          789               241275            42
6    A-02cd81          684               219304            28
7    A-02fac6          514               169854            34
8    A-034368          265                80423            25
9    A-0354fe          463               152435            30
10   A-038089          210                63673            15
11   A-039727          768               249545            32
12   A-0532a9          519               157792            30
13   A-054577          833               219747            52
14   A-05d3b3          642               193363            22
15   A-05f0e5          706               207116            46
16   A-0651a4          705               201426            37
17   A-068fc6          598               189037            29
18   A-075038          743               198728            31
19   A-089363          628               196491            33

In [49]:
account_usage = account_usage.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

In [50]:
account_usage.groupby("churn_flag")["total_usage"].mean()

churn_flag
False    495.130769
True     522.036364
Name: total_usage, dtype: float64

In [51]:
account_usage.groupby("churn_flag")["total_duration_secs"].mean()

churn_flag
False    150350.879487
True     158347.536364
Name: total_duration_secs, dtype: float64

In [52]:
account_usage.groupby("churn_flag")["total_errors"].mean()

churn_flag
False    28.230769
True     28.154545
Name: total_errors, dtype: float64

In [53]:
feature_usage["is_beta_feature"].value_counts()

is_beta_feature
False    22456
True      2544
Name: count, dtype: int64

In [5]:
beta_usage = feature_usage.merge(
    subscriptions[["subscription_id", "account_id"]],
    on="subscription_id",
    how="left"
)

In [55]:
account_beta = (
    beta_usage
    .groupby("account_id")["is_beta_feature"]
    .any()
    .reset_index(name="has_beta_usage")
)

In [56]:
account_beta = account_beta.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

In [57]:
account_beta.groupby("has_beta_usage")["churn_flag"].mean() * 100

has_beta_usage
False    12.500000
True     22.154472
Name: churn_flag, dtype: float64

In [58]:
account_beta["has_beta_usage"].value_counts()

has_beta_usage
True     492
False      8
Name: count, dtype: int64

In [6]:
beta_adoption = (
    beta_usage[beta_usage["is_beta_feature"]]
    .groupby("account_id")
    .size()
    .reset_index(name="beta_usage_count")
)

In [7]:
beta_adoption.head(20)

   account_id  beta_usage_count
0    A-00bed1                 2
1    A-00cac8                 7
2    A-0158bb                 3
3    A-016043                 3
4    A-019782                 3
5    A-029f69                 9
6    A-02cd81                 5
7    A-02fac6                 5
8    A-034368                 4
9    A-0354fe                 3
10   A-038089                 1
11   A-039727                 3
12   A-0532a9                 7
13   A-054577                10
14   A-05d3b3                 4
15   A-05f0e5                 9
16   A-0651a4                 8
17   A-068fc6                 5
18   A-075038                 9
19   A-089363                 9

In [8]:
beta_adoption = beta_adoption.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

In [9]:
beta_adoption.groupby("churn_flag")["beta_usage_count"].mean()

churn_flag
False    5.067885
True     5.532110
Name: beta_usage_count, dtype: float64

In [10]:
feature_usage["feature_name"].value_counts()

feature_name
feature_12    659
feature_32    659
feature_6     655
feature_17    651
feature_34    650
feature_26    649
feature_36    648
feature_31    644
feature_20    643
feature_24    643
feature_38    643
feature_11    643
feature_2     642
feature_15    640
feature_29    640
feature_37    636
feature_22    636
feature_33    635
feature_10    634
feature_39    631
feature_30    629
feature_1     629
feature_4     625
feature_9     624
feature_28    623
feature_16    622
feature_40    621
feature_7     619
feature_25    615
feature_13    612
feature_27    611
feature_14    600
feature_3     598
feature_8     596
feature_21    591
feature_19    589
feature_18    588
feature_35    587
feature_5     577
feature_23    563
Name: count, dtype: int64

In [11]:
feature_breadth = (
    feature_usage
    .groupby("subscription_id")["feature_name"]
    .nunique()
    .reset_index(name="unique_features_used")
)

In [12]:
feature_breadth.head(20)

   subscription_id  unique_features_used
0         S-001561                     5
1         S-0027d3                     3
2         S-003647                     8
3         S-003fc0                     4
4         S-004d19                     2
5         S-004eb4                     7
6         S-006908                     1
7         S-006fed                     9
8         S-007e2c                     5
9         S-00837c                     4
10        S-00866d                     3
11        S-008cab                     9
12        S-008f3c                     1
13        S-009027                     5
14        S-00ab51                     4
15        S-00b0bc                     1
16        S-00bb84                     7
17        S-00dea4                     5
18        S-00f31d                     4
19        S-00fb6e                     5

In [13]:
feature_breadth = feature_breadth.merge(
    subscriptions[["subscription_id", "account_id"]],
    on="subscription_id",
    how="left"
)

In [14]:
account_feature_breadth = (
    feature_breadth
    .groupby("account_id")["unique_features_used"]
    .mean()
    .reset_index(name="avg_unique_features_used")
)

In [15]:
account_feature_breadth = account_feature_breadth.merge(
    accounts[["account_id", "churn_flag"]],
    on="account_id",
    how="left"
)

In [16]:
account_feature_breadth.groupby("churn_flag")["avg_unique_features_used"].mean()

churn_flag
False    4.736216
True     4.765726
Name: avg_unique_features_used, dtype: float64

In [17]:
accounts["churn_flag"].mean() * 100

np.float64(22.0)

In [22]:
devtools_reasons = (
    churn_analysis[churn_analysis["industry"] == "DevTools"]
    ["reason_code"]
    .value_counts()
)

In [23]:
devtools_reasons

reason_code
budget        27
support       27
features      26
competitor    25
pricing       22
unknown       15
Name: count, dtype: int64

In [25]:
pd.crosstab(
    churn_analysis["industry"],
    churn_analysis["preceding_upgrade_flag"],
    normalize="index"
) * 100

preceding_upgrade_flag      False      True
industry
Cybersecurity           83.333333  16.666667
DevTools                83.098592  16.901408
EdTech                  70.707071  29.292929
FinTech                 82.031250  17.968750
HealthTech              75.675676  24.324324

In [26]:
pd.crosstab(
    churn_analysis["industry"],
    churn_analysis["preceding_downgrade_flag"],
    normalize="index"
) * 100

preceding_downgrade_flag      False      True
industry
Cybersecurity             90.833333   9.166667
DevTools                  88.732394  11.267606
EdTech                    88.888889  11.111111
FinTech                   95.312500   4.687500
HealthTech                91.891892   8.108108

In [27]:
pd.crosstab(
    churn_analysis["industry"],
    churn_analysis["is_reactivation"],
    normalize="index"
) * 100

is_reactivation      False      True
industry
Cybersecurity    90.833333   9.166667
DevTools         90.845070   9.154930
EdTech           85.858586  14.141414
FinTech          90.625000   9.375000
HealthTech       90.090090   9.909910

In [28]:
accounts["churn_flag"].mean() * 100

np.float64(22.0)

In [29]:
industry_churn = (
    accounts
    .groupby("industry")["churn_flag"]
    .mean()
    .mul(100)
    .reset_index(name="churn_rate")
    .sort_values("churn_rate", ascending=False)
)

In [30]:
industry_churn

        industry  churn_rate
1       DevTools   30.973451
3        FinTech   22.321429
4     HealthTech   21.875000
2         EdTech   16.455696
0  Cybersecurity   16.000000

In [31]:
overall_churn = accounts["churn_flag"].mean() * 100

overall_churn

np.float64(22.0)

In [32]:
summary = {
    "total_accounts": len(accounts),
    "total_churned": accounts["churn_flag"].sum(),
    "overall_churn_rate": overall_churn,
    "highest_churn_industry": industry_churn.iloc[0]["industry"],
    "highest_industry_churn_rate": industry_churn.iloc[0]["churn_rate"]
}

summary

{'total_accounts': 500,
 'total_churned': np.int64(110),
 'overall_churn_rate': np.float64(22.0),
 'highest_churn_industry': 'DevTools',
 'highest_industry_churn_rate': np.float64(30.973451327433626)}

In [33]:
churn_reason_summary = (
    churn_events["reason_code"]
    .value_counts()
    .reset_index()
)

churn_reason_summary.columns = ["reason_code", "churn_events"]

churn_reason_summary

  reason_code  churn_events
0    features           114
1     support           104
2      budget           104
3     unknown            95
4  competitor            92
5     pricing            91

In [34]:
devtools_reason_summary = (
    churn_analysis[churn_analysis["industry"] == "DevTools"]
    ["reason_code"]
    .value_counts()
    .reset_index()
)

devtools_reason_summary.columns = ["reason_code", "churn_events"]

devtools_reason_summary

  reason_code  churn_events
0      budget            27
1     support            27
2    features            26
3  competitor            25
4     pricing            22
5     unknown            15